#!/usr/bin/env bash
# SSR per-user rate-limit management panel.
set -euo pipefail

BASE_DIR="/root/speex"
PY_SCRIPT="$BASE_DIR/ssr_rate_limit.py"
CONFIG="$BASE_DIR/ssr_rate_limit.conf"
CRON_TAG="$PY_SCRIPT"
PYTHON="/usr/bin/python3"

if [[ $EUID -ne 0 ]]; then
    echo "请使用 root 运行此面板。"
    exit 1
fi

# Keep the complete implementation in this one downloadable shell file.
mkdir -p "$BASE_DIR"
cat > "$PY_SCRIPT" <<'SSR_RATE_LIMIT_PYTHON'
#!/usr/bin/env python3
"""Per-user SSR rate limiter. Generated by ssr_rate_limit.sh."""
import fcntl
import json
import os
import sys
import tempfile
import time

DB_PATH = "/usr/local/shadowsocksr/mudb.json"
BASE_DIR = "/root/speex"
STATE_PATH = os.path.join(BASE_DIR, "ssr_rate_limit_state.json")
LOCK_PATH = os.path.join(BASE_DIR, "ssr_rate_limit.lock")
WINDOW_SECONDS = int(os.environ.get("SSR_WINDOW_MINUTES", "10")) * 60
THRESHOLD_BYTES = int(os.environ.get(
    "SSR_DOWNLOAD_THRESHOLD_GB",
    os.environ.get("SSR_DOWNLOAD_THRESHOLD_GIB", "3"),
)) * 1024**3
LIMIT_SPEED = int(os.environ.get("SSR_LIMIT_SPEED", "2000"))
LIMIT_SECONDS = int(os.environ.get("SSR_LIMIT_SECONDS", "1200"))


def atomic_json(path, value, mode=0o600):
    fd, tmp_path = tempfile.mkstemp(prefix=".ssr-limit-", dir=os.path.dirname(path))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            json.dump(value, stream, ensure_ascii=False, indent=2)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(tmp_path, mode)
        os.replace(tmp_path, path)
    finally:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)


def read_state():
    try:
        with open(STATE_PATH, encoding="utf-8") as stream:
            state = json.load(stream)
        if isinstance(state, dict):
            return state
    except (OSError, ValueError):
        pass
    return {"samples": {}, "active": {}}


def main():
    os.makedirs(BASE_DIR, mode=0o700, exist_ok=True)
    with open(LOCK_PATH, "a", encoding="ascii") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        try:
            with open(DB_PATH, encoding="utf-8") as stream:
                users = json.load(stream)
            if not isinstance(users, list):
                raise ValueError("mudb.json must contain a JSON list")

            now = int(time.time())
            state = read_state()
            samples = state.setdefault("samples", {})
            active = state.setdefault("active", {})
            restore_all = len(sys.argv) > 1 and sys.argv[1] == "--restore-all"
            current_ports = set()
            changed = False

            for user in users:
                if not isinstance(user, dict) or "port" not in user:
                    continue
                port = str(user["port"])
                current_ports.add(port)
                if restore_all:
                    limit = active.pop(port, None)
                    if limit is not None:
                        user["speed_limit_per_user"] = int(limit["original"])
                        changed = True
                    continue

                downloaded = int(user.get("d", 0))
                history = samples.setdefault(port, [])
                previous = history[-1][1] if history else downloaded
                history.append([now, downloaded, max(0, downloaded - previous)])
                cutoff = now - WINDOW_SECONDS
                history[:] = [row for row in history if row[0] >= cutoff]
                window_bytes = sum(row[2] for row in history)

                if len(history) > 1 and window_bytes >= THRESHOLD_BYTES and port not in active:
                    active[port] = {
                        "started": now,
                        "until": now + LIMIT_SECONDS,
                        "speed": LIMIT_SPEED,
                        "original": int(user.get("speed_limit_per_user", 0) or 0),
                    }
                    print("LIMIT port={} bytes_10m={} speed={}".format(
                        port, window_bytes, LIMIT_SPEED))

                limit = active.get(port)
                if limit:
                    if now >= int(limit["until"]):
                        user["speed_limit_per_user"] = int(limit["original"])
                        del active[port]
                        changed = True
                        print("RESTORE port={} speed={}".format(
                            port, user["speed_limit_per_user"]))
                    elif int(user.get("speed_limit_per_user", 0) or 0) != LIMIT_SPEED:
                        user["speed_limit_per_user"] = LIMIT_SPEED
                        changed = True

            for port in list(samples):
                if port not in current_ports:
                    del samples[port]
            for port in list(active):
                if port not in current_ports:
                    del active[port]

            if changed:
                mode = os.stat(DB_PATH).st_mode & 0o777
                atomic_json(DB_PATH, users, mode)
            if restore_all:
                active.clear()
            atomic_json(STATE_PATH, state)
        finally:
            fcntl.flock(lock, fcntl.LOCK_UN)


if __name__ == "__main__":
    main()
SSR_RATE_LIMIT_PYTHON
chmod 700 "$PY_SCRIPT"

if [[ ! -x "$PYTHON" ]]; then
    PYTHON="$(command -v python3 || true)"
fi
if [[ -z "$PYTHON" || ! -f "$PY_SCRIPT" ]]; then
    echo "找不到 Python3 或 $PY_SCRIPT"
    exit 1
fi

install_cron() {
    local window="$1" threshold="$2" speed="$3" restore="$4" old_cron new_cron
    old_cron="$(crontab -l 2>/dev/null || true)"
    new_cron="$(printf '%s\n' "$old_cron" | awk -v tag="$CRON_TAG" 'index($0, tag) == 0 && $0 != ""')"
    new_cron+="${new_cron:+$'\n'}*/2 * * * * SSR_WINDOW_MINUTES=$window SSR_DOWNLOAD_THRESHOLD_GB=$threshold SSR_LIMIT_SPEED=$speed SSR_LIMIT_SECONDS=$((restore * 60)) $PYTHON $PY_SCRIPT >> $BASE_DIR/ssr_rate_limit.log 2>&1"
    printf '%s\n' "$new_cron" | crontab -
    printf 'WINDOW_MINUTES=%s\nTHRESHOLD_GB=%s\nLIMIT_SPEED=%s\nRESTORE_MINUTES=%s\n' \
        "$window" "$threshold" "$speed" "$restore" > "$CONFIG"
    chmod 600 "$CONFIG"
    echo "已设置每 2 分钟检测一次，并写入 root 定时任务。"
}

read_positive() {
    local prompt="$1" default="$2" value
    while true; do
        read -r -p "$prompt（默认 $default）: " value
        value="${value:-$default}"
        if [[ "$value" =~ ^[0-9]+$ ]] && (( value > 0 )); then
            REPLY="$value"
            return
        fi
        echo "请输入大于 0 的整数。"
    done
}

show_status() {
    echo "配置："
    if [[ -f "$CONFIG" ]]; then
        sed 's/^/  /' "$CONFIG"
    else
        echo "  尚未配置"
    fi
    if crontab -l 2>/dev/null | grep -Fq "$CRON_TAG"; then
        echo "定时任务：已启用（每 2 分钟）"
    else
        echo "定时任务：未启用"
    fi
    if [[ -f "$BASE_DIR/ssr_rate_limit_state.json" ]]; then
        "$PYTHON" - "$BASE_DIR/ssr_rate_limit_state.json" "$CONFIG" <<'SSR_STATUS_PYTHON'
import datetime
import json
import os
import sys

with open(sys.argv[1], encoding="utf-8") as stream:
    active = json.load(stream).get("active", {})
config = {}
if os.path.exists(sys.argv[2]):
    with open(sys.argv[2], encoding="utf-8") as stream:
        config = dict(line.strip().split("=", 1) for line in stream if "=" in line)
restore_seconds = int(config.get("RESTORE_MINUTES", "20")) * 60
default_speed = config.get("LIMIT_SPEED", "2000")
fmt = lambda stamp: datetime.datetime.fromtimestamp(stamp).strftime("%Y-%m-%d %H:%M:%S")
if not active:
    print("当前限速端口：无")
else:
    print("当前限速端口：")
    for port, item in sorted(active.items(), key=lambda pair: int(pair[0])):
        until = int(item["until"])
        started = int(item.get("started", until - restore_seconds))
        print("  端口 {}：限速 {}，开始 {}，预计解禁 {}".format(
            port, item.get("speed", default_speed), fmt(started), fmt(until)))
SSR_STATUS_PYTHON
    fi
}

while true; do
    echo
    echo "====== SSR 用户限速管理 ======"
    echo "1. 启用默认限速策略（10 分钟 / 3 GB / 2000 / 20 分钟恢复）"
    echo "2. 查看状态"
    echo "3. 停止策略并移除定时任务"
    echo "4. 设置限速参数并创建定时任务"
    echo "0. 退出"
    read -r -p "请选择: " choice
    case "$choice" in
        1)
            install_cron 10 3 2000 20
            ;;
        2)
            show_status
            ;;
        3)
            "$PYTHON" "$PY_SCRIPT" --restore-all
            old_cron="$(crontab -l 2>/dev/null || true)"
            new_cron="$(printf '%s\n' "$old_cron" | awk -v tag="$CRON_TAG" 'index($0, tag) == 0 && $0 != ""')"
            printf '%s\n' "$new_cron" | crontab -
            rm -f "$CONFIG"
            echo "已恢复当前限速用户的原速度并移除定时任务。"
            ;;
        4)
            read_positive "输入轮巡时间（分钟）" 10; window="$REPLY"
            read_positive "输入限制流量（GB）" 3; threshold="$REPLY"
            read_positive "输入限制速度" 2000; speed="$REPLY"
            read_positive "输入多久恢复（分钟）" 20; restore="$REPLY"
            install_cron "$window" "$threshold" "$speed" "$restore"
            ;;
        0)
            exit 0
            ;;
        *)
            echo "无效选项，请输入 1、2、3、4 或 0。"
            ;;
    esac
done
